[env:main]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#v1.2.0-gcc12
board = pico
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp>
lib_deps =
  pololu/VL53L1X
  pololu/VL53L0X
  arduino-libraries/Servo 