[env:main]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#v1.2.0-gcc12
board = rpipicow
framework = arduino
upload_protocol = picotool
monitor_speed = 115200
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
build_src_filter = +<main.cpp>
build_flags =
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
    -DBTSTACK_FILE__="main.cpp"
lib_deps =
    pololu/VL53L1X
