[env:esp32_beacon]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<esp32_beacon.cpp>
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.1

[env:pico_scanner]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#v1.2.0-gcc12
board = rpipicow
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
build_src_filter = +<pico_scanner.cpp>
build_flags =
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
    -DBTSTACK_FILE__="pico_scanner.cpp"